"""owner_id_not_null

Revision ID: 4dbe498732e5
Revises: 05f171f9c6e8
Create Date: 2026-03-10 18:32:43.107959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbe498732e5'
down_revision: Union[str, Sequence[str], None] = '05f171f9c6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
